# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - clippyasst

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: Print environment variables
        run: |
          echo "mongoURI: $MONGODB_URI"
          echo "REDISCLIENT: $IOREDIS"

      - name: npm install, build, and test
        env:  # Add environment variables here
          mongoURI: ${{secrets.MONGODB_URI}}
          REDISCLIENT: ${{secrets.IOREDIS}}
        
        run: |
          npm install
          npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9555DDCF1A4F4AF4993454B62BFA557A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF05D63ADBF24C86848467E5C9134214 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E6A7AF7D3A9847458545CBAFFEBDBA37 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'clippyasst'
          slot-name: 'Production'
          package: .
          
    
